name: CI
on:
  schedule:
    - cron: '30 5 * * *'

  push:
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - '**.cfg'
      - '**.nims'
      - '**.nim'
      - '**.nimble'
      - 'tests/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        nim: [version-2-0, version-1-6, version-1-4, version-1-2, version-1-0]
    name: '${{ matrix.os }} (${{ matrix.nim }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: project

      - name: Setup Nim
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.nim }}

      - name: Run tests
        shell: bash
        run: |
          cd project
          git fetch --unshallow
          nimble --accept build
          nimble --accept install "https://github.com/disruptek/balls"
          balls

      - name: Build docs
        if: ${{ matrix.docs }} == 'true'
        shell: bash
        run: |
          cd project
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --project --outdir:docs \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            bump.nim
          # Ignore failures for older Nim
          cp docs/{the,}index.html || true

      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/master' &&
          matrix.target == 'ubuntu-latest' && matrix.nim == 'version-2-0'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: project/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
